=== satu0king/Column-Store/schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns="http://www.CStore.com"
    targetNamespace="http://www.CStore.com"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:cstore="http://www.CStore.com"
    elementFormDefault="qualified">

    <xsd:complexType name="table_column_type">
        <xsd:sequence>

            <xsd:element name="column_name" minOccurs="1" maxOccurs="1">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[a-zA-Z][a-zA-Z0-9_]*[a-zA-Z0-9]"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>

            <xsd:element name="data_type" minOccurs="1" maxOccurs="1">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="string[0-9]+|int|float"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>

        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="table_type">
        <xsd:sequence>

            <xsd:element name="table_name" minOccurs="1" maxOccurs="1">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[a-zA-Z][a-zA-Z0-9_]*[a-zA-Z0-9]"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>

            <xsd:element name="columns" minOccurs="1" maxOccurs="1">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="column" type="table_column_type" minOccurs="1" maxOccurs="unbounded"/>
                    </xsd:sequence>
                </xsd:complexType>

                <xsd:key name="PK_table_column_name">
                    <xsd:selector xpath="cstore:column"/>
                    <xsd:field xpath="cstore:column_name"/>
                </xsd:key>
            </xsd:element>

            <xsd:element name="primary_key" type="xsd:string" minOccurs="1" maxOccurs="1"/>

            <xsd:element name="foreign_keys" minOccurs="0" maxOccurs="1">
                <xsd:complexType>
                    <xsd:sequence>

                        <xsd:element name="foreign_key" minOccurs="1" maxOccurs="unbounded">
                            <xsd:complexType>
                                <xsd:sequence>
                                    <xsd:element name="FK_from" type="xsd:string" minOccurs="1" maxOccurs="1"/>
                                    <xsd:element name="FK_table" type="xsd:string" minOccurs="1" maxOccurs="1"/>
                                    <xsd:element name="FK_to" type="xsd:string" minOccurs="1" maxOccurs="1"/>
                                </xsd:sequence>
                            </xsd:complexType>
                        </xsd:element>

                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="projection_column_type">
        <xsd:sequence>

            <xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1"/>

            <xsd:element name="table_name" type="xsd:string" minOccurs="1" maxOccurs="1"/>

            <xsd:element name="column_name" minOccurs="1" maxOccurs="1">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[a-zA-Z][a-zA-Z0-9_]*[a-zA-Z0-9]"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>

            <xsd:element name="encoding" minOccurs="0" maxOccurs="1">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="RLE"/>
                        <xsd:enumeration value="bitmap"/>
                        <xsd:enumeration value="delta"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>

        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="projection_type">
        <xsd:sequence>
        
            <xsd:element name="projection_name" minOccurs="1" maxOccurs="1">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[a-zA-Z][a-zA-Z0-9_]*[a-zA-Z0-9]"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>

            <xsd:element name="tables" minOccurs="1" maxOccurs="1">
                <xsd:complexType>
                    <xsd:sequence>

                        <xsd:element name="base_table" type="xsd:string" minOccurs="1" maxOccurs="1"/>

                        <xsd:element name="join_tables" minOccurs="0" maxOccurs="1">
                            <xsd:complexType>
                                <xsd:sequence>
                                    <xsd:element name="table" minOccurs="1" maxOccurs="unbounded">
                                        <xsd:complexType>
                                            <xsd:sequence>
                                                <xsd:element name="FK_from" type="xsd:string" minOccurs="1" maxOccurs="1"/>
                                                <xsd:element name="FK_table" type="xsd:string" minOccurs="1" maxOccurs="1"/>
                                                <xsd:element name="FK_to" type="xsd:string" minOccurs="1" maxOccurs="1"/>
                                            </xsd:sequence>
                                        </xsd:complexType>
                                    </xsd:element>
                                </xsd:sequence>
                            </xsd:complexType>
                        </xsd:element>

                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

            <xsd:element name="columns" minOccurs="1" maxOccurs="1">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="column" type="projection_column_type" minOccurs="1" maxOccurs="unbounded"/>
                    </xsd:sequence>
                </xsd:complexType>

                <xsd:key name="PK_projection_column_name">
                    <xsd:selector xpath="cstore:column"/>
                    <xsd:field xpath="cstore:name"/>
                </xsd:key>
            </xsd:element>

            <xsd:element name="sort_key" type="xsd:string" minOccurs="1" maxOccurs="1"/>

            <xsd:element name="join_indexes" minOccurs="0" maxOccurs="1">
                <xsd:complexType>
                    <xsd:sequence>

                        <xsd:element name="join_index" minOccurs="1" maxOccurs="unbounded">
                            <xsd:complexType>
                                <xsd:sequence>
                                    <xsd:element name="from" type="xsd:string" minOccurs="1" maxOccurs="1"/>
                                    <xsd:element name="other_projection" type="xsd:string" minOccurs="1" maxOccurs="1"/>
                                    <xsd:element name="to" type="xsd:string" minOccurs="1" maxOccurs="1"/>
                                </xsd:sequence>
                            </xsd:complexType>
                        </xsd:element>

                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:element name="schema">
        <xsd:complexType>
            <xsd:sequence>

                <xsd:element name="tables" minOccurs="1" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="table" type="table_type" minOccurs="1" maxOccurs="unbounded">
                                <xsd:keyref name="FK_primary_key_to_column_name" refer="PK_table_column_name">
                                    <xsd:selector xpath="."/>
                                    <xsd:field xpath="cstore:primary_key"/>
                                </xsd:keyref>
                                
                                <xsd:keyref name="FK_FK_from_to_column_name" refer="PK_table_column_name">
                                    <xsd:selector xpath="cstore:foreign_keys/cstore:foreign_key"/>
                                    <xsd:field xpath="cstore:FK_from"/>
                                </xsd:keyref>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>

                    <xsd:key name="PK_table_name">
                        <xsd:selector xpath="cstore:table"/>
                        <xsd:field xpath="cstore:table_name"/>
                    </xsd:key>
                                
                    <xsd:keyref name="FK_FK_table_to_table_name" refer="PK_table_name">
                        <xsd:selector xpath="cstore:table/cstore:foreign_keys/cstore:foreign_key"/>
                        <xsd:field xpath="cstore:FK_table"/>
                    </xsd:keyref>
                </xsd:element>

                <xsd:element name="projections" minOccurs="1" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="projection" type="projection_type" minOccurs="1" maxOccurs="unbounded">
                                <xsd:keyref name="FK_sort_key_column_name_to_projection_column_name" refer="PK_projection_column_name">
                                    <xsd:selector xpath="."/>
                                    <xsd:field xpath="cstore:sort_key"/>
                                </xsd:keyref>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>

                    <xsd:key name="PK_projection_name">
                        <xsd:selector xpath="cstore:projection"/>
                        <xsd:field xpath="cstore:projection_name"/>
                    </xsd:key>

                    <xsd:keyref name="FK_other_projection_to_projection_name" refer="PK_projection_name">
                        <xsd:selector xpath="cstore:projection/cstore:join_indexes/cstore:join_index"/>
                        <xsd:field xpath="cstore:other_projection"/>
                    </xsd:keyref>
                </xsd:element>
            
            </xsd:sequence>
        </xsd:complexType>

        <xsd:keyref name="FK_base_table_to_table_name" refer="PK_table_name">
            <xsd:selector xpath="cstore:projections/cstore:projection/cstore:tables"/>
            <xsd:field xpath="cstore:base_table"/>
        </xsd:keyref>

        <xsd:keyref name="FK_projection_FK_table_to_table_name" refer="PK_table_name">
            <xsd:selector xpath="cstore:projections/cstore:projection/cstore:tables/cstore:join_tables/cstore:table"/>
            <xsd:field xpath="cstore:FK_table"/>
        </xsd:keyref>

        <xsd:keyref name="FK_column_table_name_to_table_name" refer="PK_table_name">
            <xsd:selector xpath="cstore:projections/cstore:projection/cstore:columns/cstore:column"/>
            <xsd:field xpath="cstore:table_name"/>
        </xsd:keyref>

        <xsd:keyref name="FK_sort_key_table_name_to_table_name" refer="PK_table_name">
            <xsd:selector xpath="cstore:projections/cstore:projection/cstore:sort_key"/>
            <xsd:field xpath="cstore:table_name"/>
        </xsd:keyref>
    </xsd:element>

</xsd:schema>

=== satu0king/Column-Store/schema2.xml
<?xml version="1.0" encoding="utf-8"?>
<schema xmlns="http://www.CStore.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:cstore="http://www.CStore.com"
    xsi:schemaLocation="http://www.CStore.come schema.xsd">

    <tables>
        <table>
            <table_name>TABLE1</table_name>

            <columns>
                <column>
                    <column_name>id</column_name>
                    <data_type>int</data_type>
                </column>
                <column><column_name>col0</column_name><data_type>int</data_type></column> 
                <column><column_name>col1</column_name><data_type>int</data_type></column> 
                <column><column_name>col2</column_name><data_type>int</data_type></column> 
                <column><column_name>col3</column_name><data_type>int</data_type></column> 
                <column><column_name>col4</column_name><data_type>int</data_type></column> 
                <column><column_name>col5</column_name><data_type>int</data_type></column> 
                <column><column_name>col6</column_name><data_type>int</data_type></column> 
                <column><column_name>col7</column_name><data_type>int</data_type></column> 
                <column><column_name>col8</column_name><data_type>int</data_type></column> 
                <column><column_name>col9</column_name><data_type>int</data_type></column> 
                <column><column_name>col10</column_name><data_type>int</data_type></column> 
                <column><column_name>col11</column_name><data_type>int</data_type></column> 
                <column><column_name>col12</column_name><data_type>int</data_type></column> 
                <column><column_name>col13</column_name><data_type>int</data_type></column> 
                <column><column_name>col14</column_name><data_type>int</data_type></column> 
                <column><column_name>col15</column_name><data_type>int</data_type></column> 
                <column><column_name>col16</column_name><data_type>int</data_type></column> 
                <column><column_name>col17</column_name><data_type>int</data_type></column> 
                <column><column_name>col18</column_name><data_type>int</data_type></column> 
                <column><column_name>col19</column_name><data_type>int</data_type></column> 
                <column><column_name>col20</column_name><data_type>int</data_type></column> 
                <column><column_name>col21</column_name><data_type>int</data_type></column> 
                <column><column_name>col22</column_name><data_type>int</data_type></column> 
                <column><column_name>col23</column_name><data_type>int</data_type></column> 
                <column><column_name>col24</column_name><data_type>int</data_type></column> 
                <column><column_name>col25</column_name><data_type>int</data_type></column> 
                <column><column_name>col26</column_name><data_type>int</data_type></column> 
                <column><column_name>col27</column_name><data_type>int</data_type></column> 
                <column><column_name>col28</column_name><data_type>int</data_type></column> 
                <column><column_name>col29</column_name><data_type>int</data_type></column> 
                <column><column_name>col30</column_name><data_type>int</data_type></column> 
                <column><column_name>col31</column_name><data_type>int</data_type></column> 
                <column><column_name>col32</column_name><data_type>int</data_type></column> 
                <column><column_name>col33</column_name><data_type>int</data_type></column> 
                <column><column_name>col34</column_name><data_type>int</data_type></column> 
                <column><column_name>col35</column_name><data_type>int</data_type></column> 
                <column><column_name>col36</column_name><data_type>int</data_type></column> 
                <column><column_name>col37</column_name><data_type>int</data_type></column> 
                <column><column_name>col38</column_name><data_type>int</data_type></column> 
                <column><column_name>col39</column_name><data_type>int</data_type></column> 
                <column><column_name>col40</column_name><data_type>int</data_type></column> 
                <column><column_name>col41</column_name><data_type>int</data_type></column> 
                <column><column_name>col42</column_name><data_type>int</data_type></column> 
                <column><column_name>col43</column_name><data_type>int</data_type></column> 
                <column><column_name>col44</column_name><data_type>int</data_type></column> 
                <column><column_name>col45</column_name><data_type>int</data_type></column> 
                <column><column_name>col46</column_name><data_type>int</data_type></column> 
                <column><column_name>col47</column_name><data_type>int</data_type></column> 
                <column><column_name>col48</column_name><data_type>int</data_type></column> 
                <column><column_name>col49</column_name><data_type>int</data_type></column> 
                <column><column_name>col50</column_name><data_type>int</data_type></column> 
                <column><column_name>col51</column_name><data_type>int</data_type></column> 
                <column><column_name>col52</column_name><data_type>int</data_type></column> 
                <column><column_name>col53</column_name><data_type>int</data_type></column> 
                <column><column_name>col54</column_name><data_type>int</data_type></column> 
                <column><column_name>col55</column_name><data_type>int</data_type></column> 
                <column><column_name>col56</column_name><data_type>int</data_type></column> 
                <column><column_name>col57</column_name><data_type>int</data_type></column> 
                <column><column_name>col58</column_name><data_type>int</data_type></column> 
                <column><column_name>col59</column_name><data_type>int</data_type></column> 
                <column><column_name>col60</column_name><data_type>int</data_type></column> 
                <column><column_name>col61</column_name><data_type>int</data_type></column> 
                <column><column_name>col62</column_name><data_type>int</data_type></column> 
                <column><column_name>col63</column_name><data_type>int</data_type></column> 
                <column><column_name>col64</column_name><data_type>int</data_type></column> 
                <column><column_name>col65</column_name><data_type>int</data_type></column> 
                <column><column_name>col66</column_name><data_type>int</data_type></column> 
                <column><column_name>col67</column_name><data_type>int</data_type></column> 
                <column><column_name>col68</column_name><data_type>int</data_type></column> 
                <column><column_name>col69</column_name><data_type>int</data_type></column> 
                <column><column_name>col70</column_name><data_type>int</data_type></column> 
                <column><column_name>col71</column_name><data_type>int</data_type></column> 
                <column><column_name>col72</column_name><data_type>int</data_type></column> 
                <column><column_name>col73</column_name><data_type>int</data_type></column> 
                <column><column_name>col74</column_name><data_type>int</data_type></column> 
                <column><column_name>col75</column_name><data_type>int</data_type></column> 
                <column><column_name>col76</column_name><data_type>int</data_type></column> 
                <column><column_name>col77</column_name><data_type>int</data_type></column> 
                <column><column_name>col78</column_name><data_type>int</data_type></column> 
                <column><column_name>col79</column_name><data_type>int</data_type></column> 
                <column><column_name>col80</column_name><data_type>int</data_type></column> 
                <column><column_name>col81</column_name><data_type>int</data_type></column> 
                <column><column_name>col82</column_name><data_type>int</data_type></column> 
                <column><column_name>col83</column_name><data_type>int</data_type></column> 
                <column><column_name>col84</column_name><data_type>int</data_type></column> 
                <column><column_name>col85</column_name><data_type>int</data_type></column> 
                <column><column_name>col86</column_name><data_type>int</data_type></column> 
                <column><column_name>col87</column_name><data_type>int</data_type></column> 
                <column><column_name>col88</column_name><data_type>int</data_type></column> 
                <column><column_name>col89</column_name><data_type>int</data_type></column> 
                <column><column_name>col90</column_name><data_type>int</data_type></column> 
                <column><column_name>col91</column_name><data_type>int</data_type></column> 
                <column><column_name>col92</column_name><data_type>int</data_type></column> 
                <column><column_name>col93</column_name><data_type>int</data_type></column> 
                <column><column_name>col94</column_name><data_type>int</data_type></column> 
                <column><column_name>col95</column_name><data_type>int</data_type></column> 
                <column><column_name>col96</column_name><data_type>int</data_type></column> 
                <column><column_name>col97</column_name><data_type>int</data_type></column> 
                <column><column_name>col98</column_name><data_type>int</data_type></column> 
                <column><column_name>col99</column_name><data_type>int</data_type></column> 
            </columns>

            <primary_key>id</primary_key>
        </table>

    </tables>

    <projections>
        <projection>

            <projection_name>PROJECTION1</projection_name>

            <tables>
